### ISSUE TITLE
Hacking

### ISSUE THREAD

**Issue by arundhijo** [Ha3MrX/InstaBrute#13]
Bro in termux i will insert a apt-get install tor script it will say not located...that means what i can do sir... for your idea please tell me

**Comment by jrmessiah** [comment]
> Bro in termux i will insert a apt-get install tor script it will say not located...that means what i can do sir... for your idea please tell me

SMH, apt-get install is for linux. not for termux.

pkg install tor <<<< thats for termux. 

Please learn the basics before attempting to hack

**Comment by arundhijo** [comment]
Bye
